### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by TheTechRobo** [ArchiveTeam/megawarc#2]
I'm getting that error on Python3.

I cannot install python 2, as Debian Bullseye doesn't include that in the repos, and I'm too lazy to compile.

Thanks

**Comment by Arkiver2** [comment]
related to https://github.com/ArchiveTeam/megawarc/issues/3

**Comment by TheTechRobo** [comment]
closing this issue in favour of that more generic one.
